I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 132, in script
    *italic centered "Hail to thee, blithe Spirit!
Exception: Sayer '*italic' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 132, in script
    *italic centered "Hail to thee, blithe Spirit!
  File "/Users/kaia/Desktop/renpy-8.2.1-sdk/renpy/ast.py", line 2557, in execute
    Say.execute(self)
  File "/Users/kaia/Desktop/renpy-8.2.1-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/kaia/Desktop/renpy-8.2.1-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer '*italic' is not defined.

macOS-13.5-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
kiwiskins 1.0
Tue Apr 23 11:17:26 2024
